### ISSUE TITLE
Trying to run causes it to stop working immediately?

### ISSUE THREAD

**Issue by jclements2004** [XxGamerBroskixX/Discord-Nukebot#2]
I've tried running this several times, and every time it just stops working immediately, no error message given. I don't know why it's doing this, has anyone else encountered this?

**Comment by jclements2004** [comment]
Figured it out myself.

**Comment by XxGamerBroskixX** [comment]
Was it a problem on your end or what was happening?

**Comment by jclements2004** [comment]
Sorry I didn't get back to you - but yeah, on my end.
